let words1 = ['towel:毛巾',
    'mop:拖把',
    'cap:鸭舌帽',
    'chemistry:化学',
    'embarrassed:尴尬',
    'schedule:时刻表',
    'blank:空白的',
    'fever:发烧',
    'flour:面粉',
    'dough:面团',
    'listen:听',
    'carry:拿着',
    'street:街道',
    'diary:日记',
    'dangerous:危险的',
    'museum:博物馆',
    'sausage:香肠',
    'sneez:打喷嚏',
    'allergic:对过敏',
    'paint:画',
    'print:打印',
    'refrigerator:冰箱',
    'lifeguard:救生员',
    'vanilla:香草',
    'concert:音乐会',
    'promote:升职，推动',
    'band:乐队',
    'roller coaster:过山车',
    'to:后面动词一定跟原型',
    'medicine:药',
    'nationality:国籍',
    'entrance:入口',
    'credit card:信用卡',
    'cash:现金',
    'cent:美分',
    'spent:花了',
    'funeral:葬礼',
    'eraser:橡皮',
    'secretary:秘书',
    'strange:奇怪',
    'crash:坠毁',
    'cracker:饼干（薄饼 苏打饼干',
    'cookie:饼干（圆形，甜味',
    'dish:盘子（深的椭圆，放汤等',
    'plate:盘子（浅的 放主食甜点等',
    'spoon:勺子',
    'coach:教练',
    'bottle:水瓶',
    'blanket:毯子',
    'closet:壁橱',
    'glove:手套',
    'grocery:杂货',
    'grape:葡萄',
    'cereal:麦片',
    'pepper:胡椒粉',
    'soda:汽水',
    'grams:克',
    'kilogram:千克',
    'dessert:甜点',
    'instead:反而',
    'carrot:胡萝卜',
    'blond:金发',
    'cousin:表哥表弟',
    'exercise:锻炼',
    'British:英国的',
    'suit:西装',
    'necklace:项链',
    'neighbor:邻居',
    'excellent:很棒',
    'horror:恐怖',
    'scary:可怕的',
    'scared:害怕的',
    'sunrise:日出时刻',
    'accident:事故，意外',
    'afraid:害怕',
    'hiking:徒步旅行',
    'rock climbing:攀岩',
    'congratulations:恭喜',
    'competition:比赛',
    'camp:野营',
    'barbecue:烧烤',
    'bake:烤，烘焙',
    'race:赛跑',
    'awful:可怕的，很坏的，很糟糕',
    'tense:紧的，令人紧张的',
    'attract:吸引',
    'opposite:相反的',
    'weird:奇怪的',
    'bargain:交易，契约',
    'crowd:热闹,拥挤',
    'modern:现代',
    'direction:方向路线',
    'corner:拐角处',
    'straight:直行',
    'desert:沙漠',
    'wide:宽',
    'the United States:美国',
    'awesome:非常棒',
    'college:大学',
    'biology:生物',
    'science:科学',
    'grammar:语法',
    'quiz:小测验',
    'beginner:初学者',
    'physic:物理',
    'project:课题',
    'conversation:谈话',
    'classmates:同学',
    'honestly:老实说',
    'elevator:电梯',
    'flight:航班',
    'hall:走廊',
    'gate:登机口',
    'tourist:游客',
    'take a tour of:参观',
    'bacon:培根',
    'pack:打包',
    'dentist:牙医',
    'toothache:牙疼',
    'available:有空',
    'appointment:预约',
    'might:可能,也许会',
    'unfortunately:不幸的',
    'customer:顾客',
    'daily:每日',
    'regular:规律的',
    'discuss:商量.讨论',
    'several:几件',
    'snack:零食',
    'red envelope:红包',
    'dumpling:饺子',
    'such:真的',
    'bald head:秃头',
    'shampoo:洗发水',
    'downstairs:楼下',
    'upstairs:楼上',
    'garage:车库',
    'sink:水槽',
    'for sale:出售',
    'couch:沙发',
    'rent:出租',
    'dresser:柜子',
    'stupid:愚蠢的',
    'upset:不开心',
    'makeup:化妆品',
    'loud:大声',
    'thirsty:渴',
    'put a check:打勾',
    'correct:正确的',
    'circle:圆圈',
    'explain:解释',
    'letter:字母，信',
    'sentence:句子',
    'cafeteria:食堂',
    'in pairs:成对',
    'bride:新娘',
    'earn:赚得',
    'day off:休假',
    'skiing:滑雪',
    'surfing:冲浪',
    'volleyball:排球',
    'presentation:演示',
    'stopped at:去了一趟',
    'garlic:蒜',
    'headache:头疼',
    'Broadway:百老汇',
    'suitcase:手提箱',
    'escape:逃脱，溜走',
    'curtain:窗帘',
    'beard:胡子',
    'monster:怪物',
    'field:田野',
    'woods:树林',
    'castle:城堡',
    'bracelet:手链，手镯',
    'receive:接收',
    'except for:除了',
    'decide:决定',
    'horoscope:星座运势',
    'spill:弄洒了',
    'libra:天秤座',
    'probably:可能',
    'dead:死',
    'swimsuit:泳衣',
    'earrings:耳环',
    'on sale:正在出售，特价出售',
    'scarf:围巾',
    'sold:卖掉',
    'wait in line:排队',
    'stole:偷,过去式',
    'steal:偷',
    'ham:火腿',
    'dining Hall:食堂',
    'purse:手提包，钱袋',
    'set of:串',
    'toe:脚趾',
    'finger:手指',
    'stove:炉子',
    'mad:生气，疯狂',
    'fries:薯条',
    'burger:汉堡',
    'serious:严肃',
    'responsibility:负责任',
    'intelligent:有才智',
    'scooter:小摩托',
    'poke:戳',
    'stadium:体育场',
    'fantastic:很棒',
    'boxing:拳击',
    'athlete:运动员',
    'trophy:奖杯',
    'match:比赛',
    'bowl:碗',
    'can:罐子',
    'electric:电动',
    'mix:混合',
    'pan:平底锅',
    'slice:片',
    'chopsticks:筷子',
    'oven:烤箱',
    'above:在上面',
    'udon:乌冬面',
    'chef:主厨',
    'tent:帐篷',
    'photographer:摄影师',
    'front desk:前台',
    'pleased to meet you:很高兴认识你',
    'ice skating:滑冰',
    'fifth avenue:第五大道',
    'enjoy my time:过的很愉快',
    'give somebody a ride:载某人一程',
    'well know:有名',
    'a variety of:各种各样的',
    'flea market:跳蚤市场',
    'report card:成绩单',
    'water is off:停水',
    'pick up:取',
    'break up:分手',
    'dim sum:点心',
    'fried rice:炒饭',
    'fried chicken:炸鸡',
    'ocean view:海景',
    'parking lot:停车场',
    'limo:豪华轿车',
    'premiere:首映式',
    'mud:泥浆',
    'finally:终于',
    'luggage:行李',
    'NYU:纽约大学',
    'various:各种各样',
    'cycle:骑车',
    'opera:歌剧',
    'Brooklyn:布鲁克林',
    'advice:建议',
    'improve:提升',
    'certainly:当然',
    'receptionist:接待员，前台',
    'engineer:工程师',
    'program:程序',
    'department:部门',
    'discussion:讨论',
    'toothpaste:牙膏',
    'extra:多余，再多',
    'heat:暖气 高温',
    'staff:工作人员',
    'temperature:温度',
    'sightseeing:观光',
    'suppose:认为.，假说',
    'lamp:灯',
    'prepar:准备',
    'geography:地理',
    'grade:成绩',
    'graduate:毕业',
    'semester:学期',
    'diploma:毕业证',
    'Harvard:哈佛',
    'principal:校长',
    'grilled:烤的',
    'score:分数',
    'prefer:更喜欢',
    'snake:蛇',
    'possible:可能的',
    'describe:描述',
    'foggy:雾',
    'path:路径，小路',
    'pajama:睡衣',
    'printer:打印机',
    'bother:打扰',
    'battery:电池',
    'screen:屏幕',
    'attractive:有魅力的',
    'poster:海报',
    'sneaker:运动鞋',
    'jewelry:首饰',
    'sliver:银的',
    'wool:羊毛，',
    'badly:非常，严重的，',
    'leather:皮',
    'deal:成交',
    'discount:折扣',
    'mug:马克杯',
    'furniture:家具',
    'waiter:服务员',
    'consent:同意（请求）'
];
let words2 = ['granny:奶奶',
    'thanksgiving:感恩节',
    'turkey:火鸡',
    'roast:烤',
    'mooncake:月饼',
    'mashed potatoes:土豆泥',
    'pumpkin pie:南瓜派',
    'mid autumn festival:中秋节',
    'eiffel tower:埃菲尔铁塔',
    'Halloween:万圣节',
    'Thailand:泰国',
    'postcard:明信片',
    'ham:火腿',
    'guest:客人',
    'bride:新娘',
    'violin:小提琴',
    'actually:实际上,其实',
    'hobby:爱好',
    'anymore:不再',
    'anyway:不管怎样',
    'perhaps:或许',
    'photography:摄影师',
    'photograph:照片',
    'close:要好,关闭',
    'miracle:奇迹',
    'Spain:西班牙',
    'Germany:德国',
    'Italy:意大利',
    'berlin:柏林',
    'capital:首都',
    'pasta:意大利面',
    'colosseum:罗马竞技场',
    'huge:巨大',
    'pilot:飞行员',
    'adventure:冒险',
    'helicopter:直升机',
    'flown:飞的过去分词',
    'France:法国',
    'recipe:菜谱',
    'pass:通行证',
    'alcohol:酒',
    'intern:实习生',
    'attention:注意',
    'passenger:乘客',
    'especially:特别是',
    'platform:站台',
    'delay:延迟',
    'waitress:女服务员',
    'escape:逃跑',
    'spy:间谍',
    'salesperson:销售员',
    'folder:文件夹',
    'keyboard:键盘',
    'highway:高速路',
    'asked:要，让，叫',
    'suppose:猜，估计,认为，假说',
    'tire:轮胎',
    'engine:引擎',
    'lemonade:柠檬水',
    'massage:按摩',
    'by air:坐飞机',
    'pounds:英镑',
    'tram:有轨电车',
    'area:区域',
    'guide:向导，指南',
    'British:英国的',
    'supper:晚餐',
    'super:超级',
    'tube:地铁',
    'lamp:台灯',
    'carpet:地毯',
    'curtain:窗帘',
    'ceiling:天花板',
    'shorts:短裤',
    'skateboard:滑板',
    'cleaner:保洁员',
    'lie:躺,撒谎',
    'mop:拖把',
    'bucket:水桶',
    'film:电影',
    'actress:女演员',
    'astronaut:宇航员',
    'mustache:小胡子',
    'hold:举行,保留，维持',
    'latest:最新',
    'stage:舞台,阶段',
    'design:设计',
    'designer:设计师',
    'thin:瘦，苗条',
    'cotton:棉质',
    'soft:柔软',
    'good looking:长得好看',
    'heels:高跟鞋',
    'locker:储物柜',
    'teenager:青少年',
    'dorm:宿舍',
    'opposite:在对面.反对的',
    'spelling:拼写',
    'advance:高级，先进',
    'average:普通，平均',
    'workbook:练习册',
    'vocabulary:词汇',
    'advice:建议',
    'instruction:指令',
    'health:健康，健康教育课',
    'partner:搭档',
    'junior:初级',
    'trophy:奖杯',
    'credit card:信用卡',
    'jam:果酱',
    'sauce:酱',
    'brunch:早午餐',
    'yogurt:酸奶',
    'toast:吐司',
    'omelet:煎蛋饼',
    'garlic:大蒜',
    'lemon:柠檬',
    'mango:芒果',
    'curry:咖喱',
    'buffet:自助餐',
    'steak:牛排',
    'champagne:香槟',
    'steakhouse:牛排馆',
    'salmon:三文鱼',
    'mushroom:蘑菇',
    'special:特餐，特别的',
    'course:一道菜，经过，课程，',
    'seafood:海鲜',
    'spicy:辣',
    'cream:奶油',
    'service:服务',
    'horrible:糟糕,可怕',
    'drop:掉',
    'spilled:洒',
    'electricity:电',
    'roof:屋顶',
    'owner:主人',
    'yard:院子',
    'fence:栅栏',
    'garage:车库',
    'armchair:扶手椅',
    'neighborhood:附近',
    'playground:游乐场,操场',
    'block:街段，拦阻，堵塞,块',
    'stadium:体育场',
    'bill:账单',
    'shut:关上',
    'ankle:脚踝',
    'book a table:订桌',
    'nurse:护士',
    'vet:兽医',
    'vegetable:蔬菜',
    'security:安全',
    'instead:代替',
    'badminton:羽毛球',
    'borrow:借,借入',
    'lend:借,借出',
    'extra:多余的',
    'racket:球拍',
    'chess:国际象棋',
    'classical:古典音乐',
    'puzzle:拼图',
    'sailing:航行',
    'sweetest:最体贴',
    'beginner:初学者',
    'ringing:响',
    'press:按',
    'strict:严格',
    'stressful:压力很大',
    'unusual:不正常的，异常',
    'necessary:必须的，有必要的',
    'mechanic:技工',
    'occupation:职业',
    'lawyer:律师',
    'painful:痛苦',
    'decision:决定',
    'rob:抢了',
    'headline:头条',
    'robber:强盗',
    'chain:链子',
    'thief:小偷',
    'prison:监狱',
    'immediately:立即',
    'dramatic:夸张',
    'instrument:乐器',
    'drum:鼓',
    'awake:醒着',
    'scary:恐怖',
    'lion:狮子',
    'clown:小丑',
    'foreign:外，外国的',
    'president:总统',
    'talent:才华横溢',
    'forgive:原谅',
    'skate:溜冰鞋，旱冰鞋',
    'supply:用品,补给',
    'scissor:剪刀',
    'crayon:蜡笔',
    'case:盒子，案件',
    'square:正方形,广场，平方',
    'haircut:理发，发型',
    'uniform:制服',
    'round:圆形',
    'comic:漫画',
    'perfume:香水',
    'sort:种类',
    'scream:尖叫',
    'counter:柜台',
    'season:季节',
    'surfboard:冲浪板',
    'sandcastle:沙堡',
    'sunscreen:防晒霜',
    'wave:浪,招手',
    'sunset:日落',
    'insect:虫子',
    'motorcycle:摩托',
    'musical:音乐的',
    'cricket:板球,蟋蟀',
    'rugby:橄榄球',
    'vase:花瓶',
    'ruined:毁掉',
    'introduce:介绍',
    'engineering:工程学',
    'nearby:在附近',
    'guy:男的，男人，男',
    'cage:笼子',
    'meditation:冥想',
    'paparazzi:狗仔队',
    'attractive:有吸引力的，迷人,有魅力的',
    'celebrity:名人',
    'honest:老实，诚实',
    'fiance:未婚夫',
    'fiancee:未婚妻',
    'record:记录，录',
    'album:专辑',
    'prize:奖品，奖',
    'polite:有礼貌',
    'church:教堂',
    'pray:祈祷',
    'mosque:清真寺',
    'temple:寺庙',
    'template:模板',
    'landmark:地标',
    'railroad:铁路',
    'documentary:纪录片',
    'writing:文字',
    'sculpture:雕塑',
    'gallery:美术馆',
    'cabinet:柜子',
    'experience:经验',
    'land:登陆，土地，降落',
    'solo:独自的',
    'shuttle:摆渡车，短途交通',
    'farther:更远',
    'laundry:洗衣店',
    'unpack:打开，取出',
    'reserve:预订，保留',
    'patio:露台',
    'fare:票价，费用，饭菜',
    'homesick:想家',
    'farthest:最远',
    'visa:签证',
    'lotto:乐透',
    'lottery:彩票，包含lotto，都从lot来',
    'continent:大陆',
    'receipt:收据',
    'tiny:很小',
    'tuna:金枪鱼',
    'delivery:送货，输送，快递',
    'container:容器',
    'strawberry:草莓',
    'ingredient:成分，味',
    'pineapple:菠萝',
    'jar:罐子，坛子（玻璃，陶瓷）',
    'salty:咸的',
    'sour:酸的',
    'coconut:椰子',
    'flavor:味道',
    'utensil:餐具，用具',
    'location:地点，位置',
    'passenger seat:副驾驶位',
    'vegetarian:素食主义者',
    'incorrect:不正确',
    'essay:作文',
    'chapter:章节',
    'meaning:含义，意思',
    'review:复习，评论',
    'intermediate:中级',
    'professor:教授',
    'row:排',
    'written:写了，写',
    'confusing:令人困惑',
    'similar:相似',
    'translate:翻译',
    'laboratory:实验室',
    'hang out:闲逛，出去玩',
    'all sorts of:各种各样的',
    'stay fit:保持身材',
    'band aid:创可贴',
    'piece of:件，块',
    'flat tire:爆胎',
    'post office:邮局',
    'city hall:市政厅',
    'get divorced:离婚',
    'mainland:大陆',
    'get engaged:订婚',
    'shout at:骂了',
    'get dress:穿戴整齐',
    'a crowd:一群人',
    'ground floor:底楼，一楼',
    'payment methods:支付手段/方式',
    'license:执照',
    'do your laundry:洗衣服，做洗衣服的活',
    'passport control:入境护照检查',
    'public transportation:公共交通',
    "driver's license:驾照",
    'grand canyon:大峡谷',
    'the United kingdom:英国',
    'potato chips:薯片',
    'take long:花很长时间',
    'business class:商务舱',
    'river thames:泰晤士河',
    'put something away:把什么收起来',
    'bathing suit:泳衣',
    'part-time job:兼职工作',
    'full-time job:全职工作',
    'advance math:高数',
    'double sided:双面',
    'as usual:像平常一样',
    'alarm clock:闹钟',
    'too much traffic:交通非常繁忙',
    'no cigarettes:禁止吸烟',
    'smoke cigarettes:吸烟',
    'round trip:往返',
    'in traffic:堵在路上',
    'a road trip:自驾游',
    'sustainment:维持',
    'lecture:讲座'
];
let words3 = ['campus:校园',
    'research:研究，调查',
    'pick:挑选；选择',
    'attend:出席，赴',
    'certificate:证书',
    'description:描述',
    'feeling:感觉',
    'interview:面试',
    'quit:辞去，辞职，停止',
    'apply:申请',
    'engineering:工程学',
    'responsible:负责',
    'education:教育',
    'career:职业，事业，职业生涯',
    'begun:开始（过去分词）',
    'began:开始（过去式）',
    'airline:航空公司',
    'benefit:福利，好处',
    'full-time job:全职工作',
    'decision:决定',
    'away:离开',
    'accept:接受',
    'contact:联系',
    'guide:向导，导游',
    'sign:签名,符号',
    'genius:天才',
    'garbage:垃圾',
    'trash:垃圾',
    'housework:家务',
    'laundry:洗衣房',
    'messy:很乱的',
    'dust:灰尘',
    'dislike:不喜欢',
    'dishwasher:洗碗机',
    'rug:地垫，地毯',
    'carpet:地毯',
    'blanket:毯子',
    'neat:整齐',
    'vacuum:吸尘',
    'plant:植物',
    'heater:暖气',
    'pot:锅子',
    'freezer:冰柜',
    'chore:杂物，家务事',
    'speed:速度',
    'spead:传播',
    'charger:充电器',
    'headphones:耳机',
    'on mute:静音',
    'hopefully:希望，但愿',
    'coworker:同事',
    'colleague:同事（正式）',
    'Barcelona:巴萨罗那',
    'icy:结冰',
    'thunder:雷声',
    'figure:体型，数字，图形',
    'long distance relationship:异地恋',
    'almost:差不多，几乎',
    'beverage:饮料',
    'method:方式，方法',
    'flavor:味道',
    'honey:亲爱的',
    'in contact with:保持联系',
    'curly:卷曲',
    'introduce:介绍',
    'outgoing:外向',
    'vegetarian:素食主义者',
    'cheers:干杯',
    'shame:耻辱',
    'hug:拥抱',
    'refund:退款',
    'hung out:闲逛，出去玩',
    'example:例子',
    'does sth come in red:这sth有红色的吗',
    'curriculum vitae:简历',
    'throat:喉咙',
    'degree:度，程度,学位',
    'sore throat:咽喉痛',
    'bleed:流血',
    'elbow:肘部',
    'fortunately:幸运的是',
    'hurt:弄伤,伤害',
    'pharmacy:药店',
    'tissue:纸巾',
    'instruction:指令，指示',
    'Turbulence:气流',
    'shake:摇晃',
    'lightning:闪电',
    'announcement:广播',
    'bandage:绷带',
    'blow my nose:擤鼻涕',
    'issue:问题',
    'surprising:令人惊讶的',
    'social media:社交媒体',
    'post:发，帖子,邮政，公告',
    'topic:话题',
    'private:私人的',
    'communicate:交流，沟通',
    'type:打字',
    'by accident:不小心',
    'completely:完全的，彻底的,十分',
    'attachment:附件',
    'technology:科技',
    'in general:一般来说',
    'so mean:太卑鄙了',
    'asleep:睡着了',
    'comb:梳子，梳',
    'brush:刷',
    'shave:剃',
    'TV series:电视连续剧',
    'bored:无聊，闷',
    'all of a sudden:突然之间',
    'stressed:有压力的',
    'mayor:市长',
    'politic:政治',
    'politician:政治家',
    'law:法律',
    'campaign manager:竞选经理',
    'routine:日常生活，事务,常规',
    'princess:公主',
    'prince:王子',
    'cushion:坐垫',
    'palace:宫殿',
    'fight:打架',
    'besides:除了',
    'brave:勇敢',
    'look out:当心',
    'whatever:不管什么',
    'discover:发现，探索',
    'neck:脖子',
    'shoulder:肩膀',
    'toward:朝',
    'candle:蜡烛',
    'cover:覆盖',
    'fountain:喷泉',
    'wave:招手，浪',
    'shiny:闪亮',
    'celebration:庆祝会',
    'fireworks:烟火',
    'bar:吧台',
    'musician:音乐家',
    'wedding:婚礼',
    'deliver:送到',
    'holding:拿着',
    'traditional:传统的',
    'groom:新郎',
    'bride:新娘',
    'ceremony:仪式',
    'colorful:丰富多彩的',
    'cheeks:脸颊',
    'stood:站着（过去式/分词）',
    'exchange:交换',
    'relative:亲戚，相对的',
    'last:持续，最后的',
    'fancy:奢华;想要;花哨',
    'burning:灼烧',
    'seagull:海鸥',
    'splash:溅起',
    'ocean water:海水',
    'childhood:童年',
    'joke:笑话',
    'trumpet:喇叭，小号',
    'used to:习惯于，过去常常，曾经',
    'never used to:以前从不',
    'stay awake:保持清醒',
    'knee:膝盖',
    'stay up late:熬夜',
    'fry:炒',
    'frying pan:平底锅',
    'spinach:菠菜',
    'straw:吸管',
    'turtles:海龟',
    'recycled:回收',
    'rudest:最没礼貌',
    'arguing:争吵',
    'come over:看望',
    'mice:老鼠复数（mouse）',
    'babysitter:保姆',
    'annual:年度',
    'quite shy:很害羞',
    'firefighters:救火队员',
    'blind:看不见',
    'nephew:外甥，侄子',
    'retire:退休',
    'spouse:配偶',
    'niece:侄女',
    'trust:信任',
    'author:作家',
    'marriage:婚姻',
    'hold hands:牵手',
    'barber:理发师',
    'annoying:烦人的',
    'dating:约会',
    'respect:尊重',
    'tea set:茶具',
    'indecisive:优柔寡断的',
    'unfair:不公平',
    'parsnip:欧洲防风草，欧洲萝卜',
    'couple:情侣',
    'in danger:陷入危险',
    'sweatshirt:运动衫',
    'quality:质量',
    'mall:商场',
    'change:零钱',
    'checkout:收银台，检查',
    'cash register:收银台',
    'sleeve:袖子',
    'pretty:非常,蛮,漂亮',
    'quite:相当',
    'purple:紫色',
    'underwear:内衣',
    'afterwards:之后',
    'selfie:自拍',
    'stuff:东西',
    'percent:百分之',
    'pirate:海盗',
    'check in:办理值机',
    'fee:费用',
    'confuse:疑惑',
    'citizen:公民',
    'reservation:预订',
    'baggage:行李（like luggage）',
    'abroad:出国，国外',
    'embassy:大使馆',
    'spare key:备用钥匙',
    'opinion:意见',
    'broccoli:西兰花',
    'oyster:牡蛎',
    'spare:多余',
    'bird sitting:照看鸟',
    'seem:似乎',
    'leader:领导',
    'front page:首页',
    'government:政府',
    'border:边境',
    'gun:枪',
    'enemy:敌人',
    'billion:百万',
    'jail:牢，监狱（短时间',
    'court:法庭，球馆',
    'crime:罪行',
    'commom:常见的，共同的',
    'except:除了',
    'in exchange for:换取',
    'crash:撞，坠毁',
    'bomb:炸弹',
    'tiger:老虎',
    'jungle:丛林',
    'parrot:鹦鹉',
    'zebra:斑马',
    'beside:旁边',
    'dolphin:海豚',
    'giraffe:长颈鹿',
    'dirt:污垢，泥土',
    'owl:猫头鹰',
    'loudly:大声的',
    'humid:潮湿',
    'quietly:安静的',
    'penguins:企鹅',
    'ahead:前',
    'head of:在...前面',
    'backpacking:背包旅行',
    'leaf:叶子',
    'Brazil:巴西',
    'elephant:大象',
    'fewer:更少',
    'corn:玉米',
    'stream:小溪',
    'indoor:在室内',
    'sweep:扫',
    'swept:扫（过去）',
    'vacuuming:吸尘',
    'broom:扫帚',
    'however:然而，但是，不过',
    'assignment:布置作业,任务',
    'religion:宗教',
    'tax:税',
    'inches:英寸',
    'accountant:会计',
    'boxer:拳击手',
    'smoothie:奶昔',
    'caffeine:咖啡因',
    'picnic:野餐',
    'romantic:浪漫',
    'social:社交',
    'calm:冷静，平静，稳定',
    'have SB over:让sb过来',
    'kidding:开玩笑',
    'avoid:避免',
    'definitely:当然，肯定的',
    'patient:耐心',
    'annoyed:恼火，生气了',
    'helpful:有帮助的',
    'nightclub:夜店',
    'in a hurry:匆忙',
    'pay attention to:注意，关注',
    'clever:聪明',
    'smart:聪明的',
    'nightlife:夜生活',
    'careless:粗心',
    'fire you:开除你',
    'preparation:准备',
    'pay me back:还我钱',
    'shrimp:虾',
    'response:答案',
    'increase:增长',
    'imagine:想象',
    'in my opinion:在我看来',
    'balloon:气球',
    'pea:豌豆',
    'roll:面包卷',
    'cabbage:卷心菜',
    'lift:举起，电梯',
    'perform:演出',
    'plus:加上',
    'whether:是否',
    'chili:辣椒',
    'speaker:扬声器',
    'wait a while:稍等片刻',
    'reach:达到',
    'annoy:惹恼',
    'sore:疼，溃疡',
    'mood:心情',
    'grand kids:孙子们',
    'get out of:离开',
    'community:社区',
    'right next to:就在旁边',
    'parking:停车位',
    'turn down:调低',
    'get in:进来',
    'sandal:拖鞋',
    'bright:明亮',
    'going on:正在进行',
    'recycle:回收',
    'judge:评判',
    'charge:给。。。充电',
    'against:对面',
    'tapping:敲打，水龙头，利用',
    'branch:分支，分店',
    'application:申请，申请表',
    'ordinary:普通的，平凡的',
    'knowledge:知识',
    'situation:情况',
    'shake hand:握手',
    'signature:签名',
    'shook:摇，握',
    'salary:薪资',
    'hairstylist:发型师',
    'sincerely:真诚的',
    'photocopy:复印，影印',
    'concentrate:集中注意',
    'advertisement:广告',
    'greet:迎接',
    'flood:洪水',
    'solve:解决',
    'thought:看法',
    'chosen:选了',
    'disagree:不同意',
    'argue:争论',
    'suggestion:建议',
    'repair:修理',
    'get along:相处的很好',
    'publish:出版，发布'
]
let words4 = ["novels:小说",
    "performance:表演",
    "cinema:电影院",
    "comedying:喜剧片",
    "commercial:广告",
    "culture:文化",
    "orchestra:乐队，管弦乐队，交响乐团",
    "performer:表演者",
    "complain:抱怨",
    "ballet:芭蕾",
    "prank:恶作剧",
    "punish:惩罚",
    "nightmare:噩梦",
    "angel:天使",
    "illness:疾病",
    "flu:流感",
    "smooth:光滑的",
    "cough:咳嗽",
    "unpleasant:令人不愉快的",
    "step:步，",
    "wing:翅膀",
    "ambulance:救护车",
    "hole:洞",
    "lullaby:催眠曲",
    "next door:隔壁",
    "fluffy:毛茸茸",
    "fluffier:更蓬松",
    "mattress:床垫",
    "silently:默默的",
    "surprisingly:令人惊讶的",
    "whisper:小声交谈",
    "sweat:汗",
    "unluckily:不幸的是",
    "abilities:能力",
    "uninteresting:没意思",
    "brilliant:出色的",
    "extremely:及其，非常",
    "fairly:相当",
    "alike:一样",
    "nickname:绰号",
    "unemployed:失业",
    "creative:有创意",
    "curious:好奇",
    "chin:下巴",
    "bandage:绷带",
    "unbelievable:令人难以置信的",
    "teenage:十几岁的",
    "emergency:紧急情况",
    "accidentally:偶然",
    "recognize:不认识",
    "costume:服装",
    "outfit:全套服装,衣服",
    "fashionable:潮",
    "witch:巫婆，女巫",
    "tear:眼泪，撕破,tore",
    "torn:撕破了",
    "kimono:和服",
    "tight:紧的",
    "jeans:牛仔裤",
    "loose:宽松",
    "tying:系",
    "belt:腰带",
    "bat:蝙蝠",
    "sheet:床单",
    "van:面包车",
    "event:活动",
    "ring:戒指，环，铃声",
    "rarely:很少",
    "honeymoon:蜜月",
    "tradition:传统",
    "anniversary:周年纪念日，结婚纪念日",
    "lately:最近，近期",
    "arrival:到达",
    "incredible:了不起，出色",
    "peaceful:宁静,和平",
    "typical:典型的",
    "valley:山谷",
    "nowhere:无处",
    "shape:形状",
    "cabin:舱，机舱",
    "peak:山峰",
    "outdoor:户外",
    "stick:棍子,戳，贴",
    "marshmallow:棉花糖",
    "ancient:古老的",
    "pyramid:金字塔",
    "beauty:美",
    "stand:忍受，站立",
    "mosquito:蚊子",
    "underneath:底下",
    "among:里,其中",
    "butterfly:蝴蝶",
    "pile:堆",
    "gentle:温和",
    "dusty:尘土飞扬的",
    "stylish:时髦",
    "secret:秘密的",
    "realize:意识到",
    "notice:注意到，公告",
    "appear:出现",
    "criminal:罪犯",
    "garb:拿",
    "hairless:没毛",
    "exhausted:精疲力尽的",
    "unhealthy:不健康的",
    "bone:骨头",
    "cut:伤口,切",
    "medical:医学的",
    "drugs:药",
    "pill:药丸，药片",
    "drugstore:药店",
    "prescription:处方",
    "disease:疾病",
    "rare:罕见的",
    "seriously:严重的",
    "sleepy:很困",
    "aspirin:阿司匹林",
    "reunion:重逢",
    "clinic:诊所",
    "complicated:复杂",
    "organization:组织",
    "internship:实习",
    "instructor:讲师",
    "official:官方的",
    "register for:报名,注册",
    "bless you:祝福",
    "medicine test:医学测试",
    "plenty of:大量",
    "hand out:分发",
    "stand by:支持",
    "hand in:上交",
    "save money:省钱",
    "break down:分解",
    "air conditioning:空调",
    "lab:实验",
    "unit:单元",
    "essential:必需的",
    "drama:戏剧",
    "difficulty:困难",
    "agenda:议程，待办事宜",
    "decorate:装饰",
    "mail:邮寄",
    "backyard:后院",
    "grill:烧烤架,烤",
    "valuable:值钱",
    "bathtub:浴缸",
    "convenient:便利的",
    "match:匹配，比赛",
    "switch:开关，转变",
    "occasion:场合",
    "invitation:邀请",
    "narrow:狭窄",
    "commute:通勤",
    "lane:车道",
    "muscle:肌肉",
    "fiction:虚构，虚幻小说",
    "angle:角度",
    "express:表达",
    "volume:音量，体积",
    "update:更新",
    "smartphone:智能手机",
    "voicemail:语音留言",
    "attach:附",
    "accidentally:不小心，意外",
    "upgrade:升级",
    "article:文章",
    "silent:沉默的,安静的",
    "democracy:民主，民主国家",
    "state:州，国，状态",
    "local:当地，本地的",
    "election:选举",
    "currency:货币",
    "speech:演讲",
    "trich:真相",
    "vote:投票",
    "president:总统，主席，校长",
    "former:前任",
    "immigrantion:移民",
    "meant:意思是",
    "essential:必需品",
    "economy:经济",
    "shocking:令人震惊",
    "environmental:环境的",
    "mention:提到",
    "hired:雇了",
    "graphic:抓住，拿",
    "though,although:尽管，虽然",
    "succed:动词，成功",
    "act:行为，举动，幕，扮演",
    "typical:典型的，常见的",
    "expect:期望，料到",
    "recycling:回收品",
    "fear:恐惧",
    "but:但是，不过，除了…以外",
    "shark:鲨鱼",
    "anxious:焦急",
    "spider:蜘蛛",
    "attack:攻击",
    "earthquake:地震",
    "cliff:悬崖",
    "yikes:哎呀",
    "creepy:怪异",
    "terrified:吓坏了",
    "hairy:多毛的",
    "coulrophobia:小丑恐惧症",
    "character:特点，人物，性格",
    "independent:独立的",
    "audience:观众",
    "anime:日本动画片",
    "popcorn:爆米花",
    "century:世纪",
    "talent:天赋，才华",
    "countryside:乡下，农村",
    "filming:拍摄",
    "thriller:恐怖片",
    "plot:阴谋，情节",
    "universe:宇宙",
    "scientist:科学家",
    "industry:工业，行业",
    "director:主管，导演",
    "judge:评判员",
    "animate:动画化",
    "champion:冠军",
    "tournament:锦标赛",
    "compete:对抗，竞技",
    "Olympic:奥林匹克",
    "competing:参加",
    "tie:平局，领带",
    "beat:击败",
    "artistic:艺术性",
    "underdog:弱者",
    "stress out:压力过大",
    "meant to:意味着",
    "in time:及时",
    "bit me:咬了我",
    "for miles around:方圆几英里",
    "can't stand:受不了",
    "is not as good:没有那么好",
    "set it up:设置",
    "picture frame:相框",
    "by the time:到...的时候",
    "break into:闯入",
    "according to:据...说",
    "in a relationship:谈恋爱，交往",
    "soccer lover:足球爱好者",
    "be confident in:自信",
    "plug in:插入",
    "sign up:注册，报名",
    "back up:备份",
    "into you:喜欢你（俚语）",
    "tear tire:撕裂",
    "not go well:进展不顺利",
    "run from:逃避",
    "believe in:相信",
    "confident in:有信心",
    "in a pile:堆成一堆",
    "get ride of:摆脱，排除",
    "thank goodness:谢天谢地",
    "calm down:冷静下来",
    "live game:现场比赛",
    "cheer for:欢呼,加油",
    "stand up:站起来",
    "win against:战胜",
    "look up:查找",
    "in the audience:在观众席",
    "animated movie:动画电影",
    "marathon runner:马拉松选手",
    "root for:支持",
    "a big audience:一大群观众",
    "horror movie:恐怖电影",
    "close by:附近",
    "get around:出行",
    "drop off:送到，放下",
    "rush hour:高峰时间",
    "traffic jam:交通堵塞",
    "slow down:减速",
    "watch out:小心",
    "crosswalk:人行横道，斑马线",
    "speed limit:限速",
    "stop sign:停车标志",
    "speed up:加速",
    "get stuck:陷入困境，被堵，被卡",
    "traffic light:红绿灯",
    "no way:不行",
    "set a date:设定一个日期",
    "drop off me at:让我在...下车",
]

export { words1, words2, words3, words4 }